# Generated by Django 4.2.16 on 2024-12-18 04:21

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_alter_tournamentmodels_tournament_name'),
        ('a_game', '0003_alter_gamemodel_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.tournamentmodels'),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='room_name',
            field=models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=180, unique=True),
        ),
    ]
