# Generated by Django 4.2.16 on 2024-12-10 16:55

from django.conf import settings
from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(blank=True, default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True)),
                ('tournamentgame_name', models.CharField(blank=True, max_length=128, null=True)),
                ('createmodelform', models.CharField(blank=True, max_length=128, null=True)),
                ('joinmodelform', models.CharField(blank=True, max_length=128, null=True)),
                ('tournament_members', models.ManyToManyField(blank=True, related_name='tournament_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
